#!/bin/sh

set -e

echo ""
echo "--- [RUN]: Starting ..."
echo ""

# Run the script
find build/  -name "${1}"  -not -path '*dSYM/**' -prune -exec '{}' \;

# Find the corresponding answer in the answer file
printf "%s (Answer)\n" "`grep \"Problem ${1}\" Answers.txt`"


echo ""
echo "--- [RUN]: End."
echo ""

