#!/bin/sh

set -e

echo "[-----------]"
echo "[----RUN----]"
echo "[-----------]"

# Run the script
find build/  -name "${1}"  -not -path '*dSYM/**' -prune -exec '{}' \;

# Find the corresponding answer in the answer file
grep "Problem ${1}" Answers.txt
