/* 2. Even Fibonacci Numbers

Each new term in the Fibonacci sequence is
generated by adding the previous two terms. By
starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence
whose values do not exceed four million, find the
sum of the even-valued terms.

*/

#include <stdio.h>
#include <stdbool.h>


#define UPPER_LIMIT (size_t)4e6


int main(void)
{
    unsigned sum = 0;
    unsigned m = 1;
    unsigned n = 2;

    bool leave = false;
    while(!leave) {
        leave = (m >= UPPER_LIMIT || n >= UPPER_LIMIT);

        // (n & 1) checks whether the n is odd
        (n & 1) || (sum += n);

        unsigned tmp = m;
        m = n;
        n = tmp + n;
    }

    printf("Problem 002: %u\n", sum);

    return 0;
}
